version: '3.7'

services:
    cleantemplate.auth:
        image: ${DOCKER_REGISTRY-}cleantemplateauthdev
        build:
            context: .
            dockerfile: ../Presentation/CleanTemplate.Auth/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: "https://+:443;http://+:80"
        ports:
            - 5002:80
            - 5003:443
        depends_on:
            - db
    db:
        # Docker page https://hub.docker.com/_/mariadb?tab=description
        image: "mariadb:10.4.0"
        container_name: mariadbdev
        environment:
            MYSQL_DATABASE: CleanTemplate
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
            MYSQL_ROOT_PASSWORD: mariadb
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    adminer:
        # Useful tool to review the db
        # Docker page https://hub.docker.com/_/adminer/
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    mysql: