version: '3.7'

services:
    cleantemplate.api:
        image: ${DOCKER_REGISTRY-}cleantemplategraphql
        build:
            context: .
            dockerfile: ../Presentation/CleanTemplate.GraphQL/Dockerfile
        environment:
            COMPUTERNAME: "docker-compose"
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: "https://+:443;http://+:80"
            AUTHSERVER_AUTHORITY: "http://cleantemplate.auth:80"
        ports:
            - 5000:80
            - 5001:443
        depends_on:
            - cleantemplate.auth
    cleantemplate.auth:
        image: ${DOCKER_REGISTRY-}cleantemplateauth
        build:
            context: .
            dockerfile: ../Presentation/CleanTemplate.Auth/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"
            ASPNETCORE_URLS: "https://+:443;http://+:80"
        ports:
            - 5002:80
            - 5003:443
        depends_on:
            - db
    db:
        image: "postgres:12.2"
        container_name: postgresdb
        environment:
            POSTGRES_DB: CleanTemplate
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgconf:/etc/postgresql
            - pglog:/var/log/postgresql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    pgdata:
    pgconf:
    pglog: