version: '3.7'

services:
    cleantemplate.api:
        image: ${DOCKER_REGISTRY-}cleantemplategraphql
        build:
            context: .
            dockerfile: ../Services/CleanTemplate.GraphQL/Dockerfile
        environment:
            COMPUTERNAME: "docker-compose"
            ASPNETCORE_ENVIRONMENT: "Docker"
            ASPNETCORE_URLS: "http://+:80"
            AUTHSERVER_AUTHORITY: "http://cleantemplate.auth:80"
        ports:
            - 5000:80
            - 5001:443
        depends_on:
            - cleantemplate.auth
    cleantemplate.auth:
        image: ${DOCKER_REGISTRY-}cleantemplateauth
        build:
            context: .
            dockerfile: ../Services/CleanTemplate.Auth/Dockerfile
        environment:
            ASPNETCORE_ENVIRONMENT: "Docker"
            ASPNETCORE_URLS: "http://+:80"
            AUTHSERVER_AUTHORITY: "http://cleantemplate.auth:80"
        ports:
            - 5002:80
            - 5003:443
        depends_on:
            - db
    db:
        # Docker page https://hub.docker.com/_/mariadb?tab=description
        image: "mariadb:10.4.0"
        container_name: mariadb
        environment:
            MYSQL_DATABASE: CleanTemplate
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
            MYSQL_ROOT_PASSWORD: mariadb
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
    adminer:
        # Useful tool to review the db
        # Docker page https://hub.docker.com/_/adminer/
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    mysql: